zbior1=set("Ala ma kota")
zbior2=set(" i psa.")
print(zbior1)
print(zbior2)
print(zbior1|zbior2)
print(zbior1.intersection(zbior2)) # print(zbior1&zbior2)
print(zbior1.difference(zbior2)) # print(zbior1-zbior2)
print(zbior1.symmetric_difference(zbior2))

zbior1.add("9")
print(zbior1)
zbior1.discard(" ")
print(zbior1)